sion/urls.py
from django.conf.urls import url,include
from django.contrib import admin

import sion_core.urls as core

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include(core, namespace='core'))

]

sion_core/urls.py
from django.conf.urls import url
from .views import *


urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^register/', register, name='register'),
    url(r'^login/', login, name='login'),
    url(r'^logout/', logout, name='logout'),
    url(r'^register-sponsor/', register_sponsor, name='register_sponsor'),
    url(r'^register-volunteer/', register_volunteer, name='register_volunteer'),
    url(r'^register-donator/', register_donator, name='register_donator'),
    url(r'^register-organisasi/', register_organisasi, name='register-organisasi'),
    url(r'^profil-user/', profile_user, name='profil-user'),
    url(r'^profil-organisasi/', profile_org, name='profil-organisasi'),
    url(r'^profile-search/', profile_search, name='profil-org-search'),
    url(r'^donasi-organisasi/', donasi_org, name='donasi-organisasi'),
    url(r'^profil-donator-sponsor/', profile_user, name='profil-donator-sponsor'),


]

sion_core/models.py
from django.db import models, connections   

# # Create your models here.
# class Pengguna(models.Model):
#     email = models.EmailField(unique=True, primary_key=True)
#     password = models.CharField(max_length=50)
#     nama = models.CharField(max_length=100)
#     alamat_lengkap = models.TextField()

#     class Meta:
#      db_table = 'pengguna'

# class Donatur(models.Model):
#     email = models.OneToOneField(Pengguna, primary_key=True, on_delete=models.CASCADE, db_column='email')
#     saldo = models.IntegerField(default=0)

#     class Meta:
#         db_table = 'donatur'


# class Sponsor(models.Model):
#     email = models.OneToOneField(Pengguna,  primary_key=True, on_delete=models.CASCADE, db_column='email')
#     logo_sponsor = models.CharField(max_length=100)

#     class Meta:
#         db_table = 'sponsor'


# class Relawan(models.Model):
#     email = models.OneToOneField(Pengguna, primary_key=True, on_delete=models.CASCADE, db_column='email')
#     no_hp = models.CharField(max_length=20)
#     tanggal_lahir = models.DateField()

#     class Meta:
#         db_table = 'relawan'


# class KeahlianRelawan(models.Model):
#     email = models.ForeignKey(Relawan, on_delete=models.CASCADE, db_column='email')
#     keahlian = models.CharField(max_length=50)

#     class Meta:
#         db_table = 'keahlian_relawan'
#         unique_together = (('email', 'keahlian'),)


# class Organisasi(models.Model):
#     email_organisasi = models.CharField(primary_key=True, max_length=50)
#     website = models.CharField(max_length=50)
#     nama = models.CharField(max_length=50)
#     provinsi = models.CharField(max_length=50)
#     kabupaten_kota = models.CharField(max_length=50)
#     kecamatan = models.CharField(max_length=50)
#     kelurahan = models.CharField(max_length=50)
#     kode_pos = models.CharField(max_length=50)
#     status_verifikasi = models.CharField(max_length=50)

#     class Meta:
#         db_table = 'organisasi'

# class PengurusOrganisasi(models.Model):
#     email = models.OneToOneField(Pengguna, on_delete=models.CASCADE, db_column='email')
#     organisasi = models.ForeignKey(Organisasi, on_delete=models.CASCADE, db_column='organisasi')

#     class Meta:
#         db_table = 'pengurus_organisasi'

sion_core/views.py
from django.shortcuts import render, redirect, reverse
from django.contrib import messages
from django.views.decorators.csrf import csrf_exempt
from django.db import connection

# Create your views here.
response = {}

def index(request):
    return render(request, 'core_index.html')

def register(request):
    if 'logged_in' not in request.session or not request.session['logged_in']:
        return render(request, 'core_register.html')
        
    messages.info(request, "Anda sudah terdaftar dalam sistem. Silahkan logout terlebih dahulu!")
    return redirect(reverse('core:index'))
    

@csrf_exempt
def login(request):
    response = {}
    if 'logged_in' not in request.session or not request.session['logged_in']:
        if request.method == 'POST':
            cursor=connection.cursor()
            email = request.POST['email']
            password = request.POST['password']
            cursor.execute("SELECT * from SION.PENGGUNA where EMAIL='"+email+"'")
            select=cursor.fetchone()
            if select:
                cursor.execute("SELECT password from SION.PENGGUNA where EMAIL='"+email+"'")
                select=cursor.fetchone()
                if select[0] == password:
                    request.session['logged_in'] = True
                    request.session.modified = True
                    request.session["email"]=email

                    cursor.execute("SELECT nama from SION.PENGGUNA where EMAIL='"+email+"'")
                    select=cursor.fetchone()
                    request.session["nama"]=select[0]

                    cursor.execute("SELECT * from SION.RELAWAN where EMAIL='"+email+"'")
                    select=cursor.fetchone()
                    if (select):
                        request.session["role"]="relawan"
                        messages.success(request, "Anda telah berhasil login kedalam sistem")
                        return redirect(reverse('core:index'))

                    cursor.execute("SELECT * from SION.DONATUR where EMAIL='"+email+"'")
                    select=cursor.fetchone()
                    if (select):
                        request.session["role"]="donatur"
                        messages.success(request, "Anda telah berhasil login kedalam sistem")
                        return redirect(reverse('core:index'))

                    cursor.execute("SELECT * from SION.SPONSOR where EMAIL='"+email+"'")
                    select=cursor.fetchone()
                    if (select):
                        request.session["role"]="sponsor"
                        messages.success(request, "Anda telah berhasil login kedalam sistem")
                        return redirect(reverse('core:index'))

                    #IMPLEMENT PENGURUS HERE AND ORGANISASI
                    cursor.execute("SELECT * from SION.PENGURUS_ORGANISASI where EMAIL='"+email+"'")
                    select=cursor.fetchone()
                    if (select):
                        request.session["role"]="pengurus"
                        messages.success(request, "Anda telah berhasil login kedalam sistem")
                        return redirect(reverse('core:index'))

                else:
                    messages.error(request, 'Incorrect email or password.')
                    response['email'] = request.POST['email']
                    return render(request, 'core_login.html', response)
            else:
                messages.error(request, 'Incorrect email or password.')
                response['email'] = request.POST['email']
                return render(request, 'core_login.html', response)
        else:
            return render(request, 'core_login.html')

    else:
        messages.info(request,'Anda sudah masuk kedalam sistem.')
        return redirect(reverse('core:index'))
                    
def logout(request):
    messages.success(request, 'Anda berhasil keluar dari sistem.')
    request.session.flush()
    return redirect(reverse('core:index'))

@csrf_exempt
def register_sponsor(request):
    if 'logged_in' not in request.session or not request.session['logged_in']:
        if(request.method == 'POST'):
            name = request.POST["name"]
            email = request.POST["email"]
            pwd = request.POST["password"]
            address = request.POST["alamat"]
            logo = request.POST["pic"]
            kecamatan = request.POST["kecamatan"]
            kabupaten = request.POST["kabupaten"]
            kodepos = request.POST["kodepos"]

            alamat_lengkap = address+', '+ kecamatan +', '+kabupaten+', '+kodepos

            cursor = connection.cursor()
            cursor.execute("SELECT * from SION.PENGGUNA where EMAIL='"+email+"'")
            select = cursor.fetchone()
            if (select):
                messages.error(request, 'Email already registered.')
                return render(request,'register_sponsor.html',response) 
            cursor.execute("INSERT INTO SION.PENGGUNA (email,password,nama,alamat_lengkap) VALUES('"+email+"','"+pwd+"','"+name+"','"+alamat_lengkap+"')")
            cursor.execute("INSERT INTO SION.SPONSOR (email,logo_sponsor) VALUES('"+email+"','"+logo+"')")

            request.session["email"] = email
            request.session["name"] = name
            request.session["role"] = "sponsor"
            request.session["logo"] = logo
            request.session["address"] = alamat_lengkap
            request.session["logged_in"] = True
            request.session.modified = True

            messages.success(request, "Anda berhasil registrasi sebagai sponsor")
            return redirect(reverse('core:index'))
        return render(request, 'register_sponsor.html')
    messages.info(request, "Anda sudah terdaftar dalam sistem. Silahkan logout terlebih dahulu!")
    return redirect(reverse('core:index'))

@csrf_exempt
def register_volunteer(request):
    if 'logged_in' not in request.session or not request.session['logged_in']:
        if(request.method == 'POST'):
            name = request.POST["name"]
            email = request.POST["email"]
            pwd = request.POST["password"]
            address = request.POST["alamat"]
            kecamatan = request.POST["kecamatan"]
            kabupaten = request.POST["kabupaten"]
            kodepos = request.POST["kodepos"]
            ttl = request.POST["ttl"]
            keahlian = request.POST["keahlian"]
            telpon = request.POST["telpon"]

            alamat_lengkap = address+', '+ kecamatan +', '+kabupaten+', '+kodepos


            cursor = connection.cursor()
            cursor.execute("SELECT * from SION.PENGGUNA where EMAIL='"+email+"'")
            select = cursor.fetchone()
            if (select):
                messages.error(request, 'FAILED! Email already registered.')
                return render(request,'register_volunteer.html',response) 
            cursor.execute("INSERT INTO SION.PENGGUNA (email,password,nama,alamat_lengkap) VALUES('"+email+"','"+pwd+"','"+name+"','"+alamat_lengkap+"')")
            cursor.execute("INSERT INTO SION.RELAWAN (email, no_hp, tanggal_lahir) VALUES('"+email+"','"+telpon+"','"+ttl+"')")
            keahlian = keahlian.split(";")
            for i in keahlian:
                cursor.execute("INSERT INTO SION.KEAHLIAN_RELAWAN (email, keahlian)  VALUES('"+email+"','"+i+"')")

            request.session["email"] = email
            request.session["name"] = name
            request.session["role"] = "relawan"
            request.session["address"] = alamat_lengkap
            request.session["logged_in"] = True
            request.session["keahlian"] = keahlian
            request.session["ttl"] = ttl
            request.session["telpon"] = telpon
            request.session.modified = True

            messages.success(request,"Anda berhasil registrasi sebagai relawan")
            return redirect(reverse('core:index'))
        return render(request, 'register_volunteer.html')
    messages.warning(request,"Anda sudah terdaftar dalam sistem. Silahkan logout terlebih dahulu!")
    return redirect(reverse('core:index'))

@csrf_exempt
def register_donator(request):
    if 'logged_in' not in request.session or not request.session['logged_in']:
        if(request.method == 'POST'):
            name = request.POST["name"]
            email = request.POST["email"]
            pwd = request.POST["password"]
            address = request.POST["alamat"]
            kecamatan = request.POST["kecamatan"]
            kabupaten = request.POST["kabupaten"]
            kodepos = request.POST["kodepos"]

            alamat_lengkap = address+', '+ kecamatan +', '+kabupaten+', '+kodepos

            cursor = connection.cursor()
            cursor.execute("SELECT * from SION.PENGGUNA where EMAIL='"+email+"'")
            select = cursor.fetchone()
            if (select):
                messages.error(request, 'Email already registered.')
                return render(request,'register_sponsor.html',response) 
            cursor.execute("INSERT INTO SION.PENGGUNA (email,password,nama,alamat_lengkap) VALUES('"+email+"','"+pwd+"','"+name+"','"+alamat_lengkap+"')")
            cursor.execute("INSERT INTO SION.DONATUR (email,saldo) VALUES('"+email+"','0')")


            request.session["email"] = email
            request.session["name"] = name
            request.session["role"] = "donatur"
            request.session["address"] = alamat_lengkap
            request.session["logged_in"] = True
            request.session.modified = True

            messages.success(request,"Anda berhasil registrasi sebagai donatur")
            return redirect(reverse('core:index'))
        return render(request, 'register_donator.html')
    messages.warning(request,"Anda sudah terdaftar dalam sistem. Silahkan logout terlebih dahulu!")
    return redirect(reverse('core:index'))

@csrf_exempt
def register_organisasi(request):
    if 'logged_in' not in request.session or not request.session['logged_in']:

sion_core/templates/core_index.html
{% extends 'layout/core_base.html' %}
{% load static %}

{% block subtitle %}
    Home - 
{% endblock %}

{% block content %}

  {% if error_msg %}
    <div class="row bg-primary">
        <div class="col-12">
            <div class="alert alert-info">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                <p>{{ error_msg }}</p>
            </div>
        </div>
    </div>
  {% endif %}

  <div class="pt-5 text-white bg-primary">
    <div class="container">
      <div class="row">
        <div class="col-12">
            <h1 class="display-4"> <strong> SION </strong></h1>
            <hr>
        </div>
      </div>
      <div class="row">
        <div class="col-md-6 text-md-left text-center align-self-center my-5">
          <p class="lead">Selamat datang di Tugas Kelompok Basdat.Kami dari kelompok 4 kelas B mohon nilainya yang bagus ya karena capek dan pusing padahal udah ada django models tapi disuruh pake yang jadul :( huhuhu
          credits to pingendo karena anda UI/UX nya jadi 15 menit doangs.</p>

          {% if not request.session.logged_in %}
            <div class="row mt-5 bg-primary">
              <div class="col-md-5 col-6">
                <a class="btn btn-info d-inline-flex" href="/login" >Login </a>
                
                <a class="btn btn-info d-inline-flex" href="/register" >Register </a>
              
              </div>

            </div>
          {% endif %}


        </div>
        <div class="col-md-6 text-primary">
          <img class="img-responsive d-block img-fluid img-thumbnail mx-auto bg-primary" src="../static/core/img/asset-home.png"> </div>
      </div>

    </div>
  </div>

{% endblock %}

sion_core/templates/core_login.html
{% extends 'layout/core_base.html' %}
{% load static %}

{% block subtitle %}
    Login - 
{% endblock %}

{% block content %}
  {% if error_msg %}
    <div class="row">
        <div class="col-12">
            <div class="alert alert-danger">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                <p>{{ error_msg }}</p>
            </div>
        </div>
    </div>
  {% endif %}

  <div class="py-5 bg-dark">
    <div class="container">
      <div class="row">
        <div class="col-md-3"> </div>
        <div class="col-md-6">
          <div class="card text-gray p-5 bg-gray-dark">
            <div class="card-body">
              <h1 class="mb-4 text-dark">Login form</h1>
              <form action="{% url 'core:login' %}" method="post">
                {% csrf_token %}
                 <div class="form-group">
                <div class="form-group">
                  <label>Email</label>
                  <input type="text" class="form-control" placeholder="Enter Username" name="email" required="required" {% if email %} value="{{ email }}" {% endif %}> </div>
                <div class="form-group">  
                  <label>Password</label>
                  <input type="password" class="form-control" placeholder="Enter Password" required="required" name="password"> </div>
                <button type="submit" class="btn btn-grey">Login</button>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

{% endblock %}

sion_core/templates/core_register.html
{% extends 'layout/core_base.html' %}
{% load static %}

{% block subtitle %}
    Register - 
{% endblock %}

{% block content %}

  <div class="py-5">
    <div class="container">
      <div class="row">
          <div class="col-md-6">
          <a href = "/register-sponsor">
            <img class="img-fluid d-block mx-auto" src="../static/core/img/asset-donatur.png" width="300" height="300"></a>
            <h1 class="text-center">Daftar Sebagai Sponsor</h1>
          </div>
        </a>  

        <div class="col-md-6"> 
          <a href = "/register-donator">
          <img class="img-fluid d-block mx-auto" src="../static/core/img/asset-sponsor.png" width="300" height="300"></a>
          <h1 class="text-center">Daftar Sebagai Donatur</h1>
        </div>
      </div>
    </div>
  </div>
  <div class="py-5">
    <div class="container">
      <div class="row">
          <div class="col-md-6">
          <a href = "/register-volunteer">
            <img class="img-fluid d-block mx-auto" src="../static/core/img/asset-relawan.png" width="300" height="300"></a>
            <h1 class="text-center">Daftar Sebagai Relawan</h1>
          </div>
        </a>  

        <div class="col-md-6"> 
          <a href = "/register-organisasi">
          <img class="img-fluid d-block mx-auto" src="../static/core/img/asset-organisasi.png" width="300" height="300"></a>
          <h1 class="text-center">Daftar Organisasi</h1>
        </div>
      </div>
    </div>
  </div>

  {% endblock %}

sion_core/templates/profile_donator_sponsor.html
{% extends 'layout/core_base.html' %}
{% load static %}

{% block subtitle %}
    Profile -
{% endblock %}
{% block content %}
  <div class="py-5">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="py-5">
            <h1 class="text-dark" style="background:rgba(255,255,255,0.5)"> Profile </h1>
            <center class="">
              <img class="img-circle border mx-auto" width="170px" src="../static/core/img/asset-profil.jpg"> </center>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="py-5">
    <div class="container">
      <div class="row">
        <div class="col-md-12" style="background:rgba(255,255,255,0.5)">
          <div class="py-5">
            <h1 class="text-dark">Information</h1>
            <h2 class="text-dark w-25 p-2">Nama</h2>
            <p class="text-dark">{{nama}}</p>
            <h2 class="text-dark p-2 w-25">E-Mail</h2>
            <p class="text-dark">{{email}}</p>
            <h2 class="text-dark p-2 w-25">Alamat</h2>
            <p class="text-dark">{{alamat}}</p>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="py-5">
    <div class="container">
      <div class="row">
        <div class="col-md-12" style="background: rgba(255, 255, 255, 0.5);">
          <div class="py-5">
            <h1 class="text-dark">Saldo</h1>
            <h2 class="text-dark">{{saldo}}</h2>
          </div>
        </div>
      </div>
    </div>
  </div>

  {% endblock %}

sion_core/templates/profile_user.html
{% extends 'layout/core_base.html' %}
{% load static %}

{% block subtitle %}
    Profile - 
{% endblock %}
{% block content %}
  <div class="py-5">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="py-5">
            <h1 class="text-dark" style="background:rgba(255,255,255,0.5)"> Profile </h1>
            <center class="">
              <img class="img-circle border mx-auto" width="170px" src="../static/core/img/asset-profil.jpg"> </center>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="py-5">
    <div class="container">
      <div class="row">
        <div class="col-md-12" style="background:rgba(255,255,255,0.5)">
          <div class="py-5">
            <h1 class="text-dark">Information</h1>
            <h2 class="text-dark w-25 p-2">Nama</h2>
            <p class="text-dark">{{nama}}</p>
            <h2 class="text-dark p-2 w-25">E-Mail</h2>
            <p class="text-dark">{{email}}</p>
            <h2 class="text-dark p-2 w-25">Alamat</h2>
            <p class="text-dark">{{alamat}}</p>
          </div>
        </div>
      </div>
    </div>
  </div>

  {% endblock %}

sion_core/templates/register_donator.html
{% extends 'layout/core_base.html' %}
{% load static %}

{% block subtitle %}
    Register Donator - 
{% endblock %} 
{% block content %}
 <div class="align-items-center d-flex cover section-aquamarine py-5" >
    <div class="container">
      <div class="row">
        <div class="col-lg-12 p-3">
          <form class="p-4 bg-light" method="post" action="{% url 'core:register_donator' %}">
            {% csrf_token %}  
            <h4 class="mb-4 text-center">Register as a Donator</h4>
            <div class="form-group">
              <label>Name</label>
              <input class="form-control" name="name" required="required" placeholder="Your name"> </div>
            <div class="form-group">
              <label>Email</label>
              <input type="email" class="form-control" name="email" required="required" placeholder="Your email"> </div>
            <div class="form-group">
              <label>Password</label>
              <input type="password" class="form-control" name="password" required="required" placeholder="Set your password"> </div>
            <div class="form-group">
              <label>District</label>
              <input class="form-control" name="kecamatan" required="required" placeholder="Your district"> </div>
            <div class="form-group">
              <label>Regency</label>
              <input class="form-control" name="kabupaten" required="required" placeholder="Your regency"> </div>
            <div class="form-group">
              <label>Postal code</label>
              <input type="number" class="form-control" name="kodepos" required="required" placeholder="your postal code"> </div>
            <div class="form-group">
              <label>Address</label>
              <input class="form-control" name="alamat" required="required" placeholder="your address"> </div>
            <button type="submit" class="btn mt-4 btn-block p-2 btn-primary">
              <b>Register as a Donator</b>
            </button>
          </form>
        </div>
      </div>
    </div>
  </div>
  {% endblock %}

sion_core/templates/register_organisasi.html
  {% extends 'layout/core_base.html' %}
{% load static %}

{% block subtitle %}
    Register Organisasi - 
{% endblock %}
{% block content %}
 <div class="align-items-center d-flex cover section-aquamarine py-5" >
    <div class="container">
      <div class="row">
        <div class="col-lg-12 p-3">
          <form class="p-4 bg-light" method="post" action="{% url 'core:register-organisasi' %}">
            {% csrf_token %}
            <h4 class="mb-4 text-center">Register Organization</h4>
            <div class="form-group">
              <label>Organization Name</label>
              <input class="form-control" name="org_name" required="required" placeholder="Organization's name"> </div>
            <div class="form-group">
              <label>Website</label>
              <input type="url" class="form-control" name="website" required="required" placeholder="Organization's website"> </div>
            <div class="form-group">
              <label>Email</label>
              <input type="Email" class="form-control" name="org_email" required="required" placeholder="Organization's email"> </div>
            <div class="form-group">
              <label>District</label>
              <input class="form-control" name="kecamatan" required="required" placeholder="Organization's district"> </div>
            <div class="form-group">
              <label>Regency</label>
              <input class="form-control" name="kabupaten" required="required" placeholder="Organization's regency"> </div>
            <div class="form-group">
              <label>Province</label>
              <input class="form-control" name="provinsi" required="required" placeholder="Organization's province"> </div>
            <div class="form-group">
              <label>Postal code</label>
              <input type="number" class="form-control" name="kodepos" required="required" placeholder="Organization's postal code"> </div>
            <div class="form-group">
              <label>Address</label>
              <input class="form-control" name="alamat" required="required" placeholder="Organization's address"> </div>
            <div class="form-group">
              <label>Organization's Objective</label>
              <input class="form-control" name="tujuan" required="required" placeholder="Organization's objective"> </div>
            <div class="form-group">
              <label>Admin Name</label>
              <input class="form-control" name="nama_pengurus" required="required" placeholder="Admin's name"> </div>
            <div class="form-group">
              <label>Admin Password</label>
              <input type="Password" class="form-control" name="password_pengurus" required="required" placeholder="Admin's Password"> </div>
            <div class="form-group">
              <label>Admin E-mail</label>
              <input type="Email" class="form-control" name="email_pengurus" required="required" placeholder="Admin's e-mail"> </div>
            <div class="form-group">
              <label>Admin Address</label>
              <input class="form-control" name="alamat_pengurus" required="required" placeholder="Admin's address"> </div>
            <button type="submit" class="btn mt-4 btn-block p-2 btn-primary">
              <b>Register Organization</b>
            </button>
          </form>
        </div>
      </div>
    </div>
  </div>
  {% endblock %}

sion_core/templates/register_sponsor.html
{% extends 'layout/core_base.html' %}
{% load static %}

{% block subtitle %}
    Register Sponsor - 
{% endblock %}
{% block content %}

 <div class="align-items-center d-flex cover">
    <div class="container">
      <div class="row">
        <div class="col-lg-12 p-3">
          <form class="p-4 bg-light" method="post" action="{% url 'core:register_sponsor' %}">
            {% csrf_token %}
            <h4 class="mb-4 text-center">Register as a Sponsor</h4>
            <div class="form-group">
              <label>Company name</label>
              <input class="form-control" name="name" required="required" placeholder="Your company name"> </div>
            <div class="form-group">
              <label>Email</label>
              <input type="email" class="form-control" name="email" required="required" placeholder="Your company email"> </div>
            <div class="form-group">
              <label>Password</label>
              <input type="password" class="form-control" name="password" required="required" placeholder="Set your password (case sensitive)"> </div>
            <div class="form-group">
              <label>District</label>
              <input class="form-control" name="kecamatan" required="required" placeholder="Your company district"> </div>
            <div class="form-group">
              <label>Regency</label>
              <input class="form-control" name="kabupaten" required="required" placeholder="Your company regency"> </div>
            <div class="form-group">
              <label>Postal code</label>
              <input type="number" class="form-control" name="kodepos" required="required" placeholder="your company postal code"> </div>
            <div class="form-group">
              <label>Address</label>
              <input class="form-control" name="alamat" required="required" required="required" placeholder="your company address"> </div>
            <div class="form-group">
              <label>Company logo </label>
              <br><input type="file" name="pic" required="required" accept="image/*"> </div>
            <button type="submit" class="btn mt-4 btn-block p-2 btn-primary">
              <b>Register as a Sponsor</b>
            </button>
          </form>
        </div>
      </div>
    </div>
  </div>
  {% endblock %}

sion_core/templates/register_volunteer.html
{% extends 'layout/core_base.html' %}
{% load static %}

{% block subtitle %}
    Register Volunteer - 
{% endblock %}
{% block content %}
<div class="align-items-center d-flex cover section-aquamarine py-5">
    <div class="container">
      <div class="row">
        <div class="col-lg-12 p-3">
        <form class="p-4 bg-light" method="post" action="{% url 'core:register_volunteer' %}">
        {% csrf_token %}
        <h4 class="mb-4 text-center">Register as a Volunteer</h4>
        <div class="form-group">
          <label>Name</label>
          <input class="form-control" name="name" required="required" placeholder="Your name"> </div>
        <div class="form-group">
          <label>Email</label>
          <input type="email" class="form-control" name="email" required="required" placeholder="Your email"> </div>
        <div class="form-group">
          <label>Password</label>
          <input type="password" class="form-control" name="password" required="required" placeholder="Set your password"> </div>
        <div class="form-group">
          <label>District</label>
          <input class="form-control" name="kecamatan" required="required" placeholder="Your district"> </div>
        <div class="form-group">
          <label>Regency</label>
          <input class="form-control" name="kabupaten" required="required" placeholder="Your regency"> </div>
        <div class="form-group">
          <label>Postal code</label>
          <input type="number" class="form-control" name="kodepos" required="required" placeholder="your postal code"> </div>
        <div class="form-group">
          <label>Address</label>
          <input class="form-control" name="alamat" required="required" placeholder="your address"> </div>
        <div class="form-group">
          <label>Birth date</label>
          <input type="date" class="form-control" name="ttl" required="required" placeholder="your birth date"> </div>
        <div class="form-group">
          <label>Phone number</label>
          <input type="tel" class="form-control" name="telpon" required="required" placeholder="your phone number"> </div>
        <div class="form-group">
          <label>Skills (Separate with ';' if you have more than 1 skill eg: Skill 1; Skill2)</label>
          <input class="form-control" name="keahlian" required="required" placeholder="skills that you have"> </div>
        <button type="submit" class="btn mt-4 btn-block p-2 btn-primary">
          <b>Register as a Volunteer</b>
        </button>
        </form>
      </div>
      </div>
    </div>
  </div>
  {% endblock %}